-- Queries SQL
-- Considerando um banco de dados mysql ou pgsql, 
-- imagine haver uma tabela produto (id, nome, valor) e outra tabela vendas 
-- (id, data, produto_id, qtde). 
-- Monte uma query em SQL que retorne as 
-- vendas mensais de cada produto (mes, produto, qtde, valor total).
